language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby-9.2.11.1
gemfile:
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
  - gemfiles/ar60.gemfile
  - gemfiles/rgeo1.gemfile
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/ar60.gemfile
    - rvm: 2.3
      gemfile: gemfiles/ar60.gemfile
